name: Android PR Check

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".gitignore"

permissions:
  contents: read
  actions: write

env:
  APP_VARIANT: e2e
  WITH_MOCK: true
  ENCRYPTION_SALT: 0123456789abcdef
  MNEMONIC_LENGTH: 2
  CI: true

jobs:
  lint-and-doctor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Linter
        run: bun run lint

      - name: Run Expo Doctor
        run: bunx expo-doctor

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5.0.0
        with:
          cache-read-only: false

      - name: Enable KVM group perms
        run: |
          sudo chmod 666 /dev/kvm

      - name: Run E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -no-snapshot -noaudio -no-boot-anim
          disable-animations: true
          script: bun run android:e2e
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
