name: Android PR Check

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".gitignore"

permissions:
  contents: read
  actions: write

env:
  APP_VARIANT: e2e
  WITH_MOCK: true
  ENCRYPTION_SALT: 0123456789abcdef
  MNEMONIC_LENGTH: 2
  CI: true

jobs:
  lint-and-doctor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Linter
        run: bun run lint

      - name: Run Expo Doctor
        run: bunx expo-doctor

  e2e-android:
    runs-on: macos-latest
    needs: lint-and-doctor
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Setup EAS & Maestro
        run: |
          npm install -g eas-cli
          curl -FsSL https://get.maestro.mobile.dev | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5.0.0
        with:
          cache-read-only: false

      - name: Run E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: arm64-v8a
          force-avd-creation: true
          emulator-options: -no-window -no-snapshot -noaudio -no-boot-anim -no-metrics
          disable-animations: true
          script: |
            # We need EXPO_TOKEN in repository secrets so eas can download keys
            # If it's missing, eas build --local will fail during account check
            bun run android:e2e
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
